apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-ci-cd-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto-ci-cd-example
  template:
    metadata:
      labels:
        app: projeto-ci-cd-example
    spec:
      containers:
        - name: projeto-ci-cd-example
          image: gcr.io/projetoagenda/projeto-ci-cd-example:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: projeto-ci-cd-example-service
  labels:
    app: projeto-ci-cd-example
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http-svc
      port: 80
      targetPort: 8080
  selector:
    app: projeto-ci-cd-example
